### PR TITLE
cro serve / as /index.html

### PR DESCRIPTION
**Pull request by mienaikage**

### CODE REVIEW

**Comment by Altai-man** [comment]
@jnthn, what do you think about this change?

**Comment by jnthn** [comment]
Well, so far as identifying a feature we want, I agree with it. :-)

So far as the solution goes, it only covers an index in the very root, and even then only a single file extension. I think the better way to do it would be to give `static` a `:indexes` option which can be set to a list of index files, and to handle it in there. Then this `cro serve` can just use that functionality.

**Comment by Altai-man** [comment]
See https://github.com/croservices/cro-http/commit/937d8f228d69ace2c8e1bcc7533989ee27f2b745 and https://github.com/croservices/cro/commit/29fbc1c0f057bea8b7f506b7abddccdcf36401a1. @mienaikage++ for the idea.
Seems to me like we can close this PR.

**Comment by jnthn** [comment]
Should document it first; I can do that.

**Comment by jnthn** [comment]
Documented in d8810bd9cf.

**Pull request closed without merging**
